# Define environment
os: linux
dist: xenial

languague: bash

env:
  global:
    # BRANCHES VARIABLES
    - environment=""
    - branch_DEV="dev"
    - branch_PROD="prod"
    # DIRECTORIES VARIABLES
    - folder_dev="$PWD/development"
    - folder_prod="$PWD/production"
    # 1PASSWORD VARIABLES
    - onepasstool=1.8.0
    # TERRAFORM VARIABLES
    - tf_version=0.13.0
    - tf_init_cli_options="-input=false"
    - tf_validation_cli_options=""
    - tf_plan_cli_options="-lock=false -input=false"
    - tf_apply_cli_options="-auto-approve -input=false"
    - tf_var_file="./terraform.tfvars"

before_install:
  if: branch = $branch_DEV # If branch is development
    script:
      - $environment=$branch_DEV
      - cd $folder_dev
    
  if: branch IN ($branch_PROD,master) # if branches is production
    script:
      - $environment=$branch_PROD
      - cd $folder_prod
      
install: bash ./scripts/install.sh

jobs:
  include:
    - stage: terraform plan dev
      if: branch = $branch_DEV and type IN (pull_request)
        script:
          - bash ./scripts/tf-plan.sh

    - stage: terraform plan prod
      if: branch = branch_PROD and type IN (pull_request)
        script:
          - bash ./scripts/tf-plan.sh
    
    - stage: terraform apply dev
      if: (branch IN ($branch_DEV,$branch_PROD,master)) and type IN (push,merge)
        script:
          - bash ./scripts/tf-apply.sh
      