# Define environment
os: linux
dist: xenial

languague: bash

env:
  global:
    - tf_version=0.14.7
    - tf_init_cli_options="-input=false"
    - tf_validation_cli_options=""
    - tf_plan_cli_options="-lock=false -input=false"
    - tf_apply_cli_options="-auto-approve -input=false"

branches:
  only:
    - master

before_install: ./script/install.sh

jobs:
  include:
    - stage: terraform Plan
      if: type IN (pull_request)
      script: ./script/tf-plan.sh

    - stage: terraform Apply
      if: type IN (push) and branch = master
      script: ./script/tf-apply.sh
